src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Daml_Email__c</fullName>
        <label>Daml Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Demo_Email__c</fullName>
        <label>Demo Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Primary Contact)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PhoneB__c</fullName>
        <description>Phone number to display in Banner (highlights panel).
This will be chosen form available phone numbers using a trigger.</description>
        <label>Phone:</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_Phone__c</fullName>
        <formula>FinServ__PrimaryContact__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Contact Phone</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UpdatePhoneAndEmailBatchable.cls
global class UpdatePhoneAndEmailBatchable implements Database.Batchable<SObject> {

	String recordTypeName;

	global UpdatePhoneAndEmailBatchable(String recordTypeName) {
		this.recordTypeName = recordTypeName;
	}

    global Database.QueryLocator start(Database.BatchableContext BC) {

		return Database.getQueryLocator([
			SELECT
				Id,
				RecordTypeId,
				PersonContactId,
				PersonEmail,
				FinServ__PrimaryContact__c,
				Daml_Email__c,
				Demo_Email__c,
				PhoneB__c,
				Phone,
				PersonMobilePhone,
				PersonHomePhone,
				Contact_Work_Phone__pc,
				Primary_Contact_Phone__c
			FROM Account
			WHERE RecordType.Name = :recordTypeName]);
    }

    global void execute(Database.BatchableContext BC, List<Account> scope) {
		Map<Id,Account> newRecords = new Map<Id,Account>(scope);

		AccountTriggerHandler handler = new AccountTriggerHandler();
		handler.populatePhones(null,null,newRecords.values());
		handler.populateEmails(null,null,newRecords.values());
		update newRecords.values();

		handler.populatePersonEmail(null,newRecords);
    }

    global void finish(Database.BatchableContext BC) {
    }
}