src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Split__c.object
<CustomObject>
    <fields>
        <fullName>Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Account Split IDs</relationshipLabel>
        <relationshipName>Account_Split_IDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Split ID</label>
    <nameField>
        <label>Account Split Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Split IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assistant_Assignment__c.object
<CustomObject>
    <description>Designates that a user is another user&apos;s assistant. A user can have multiple assistants and a user can be the assistant for multiple other users, so this is a junction object.</description>
    <label>Assistant Assignment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Assistant Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistant Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rep__c.object
<CustomObject>
    <description>Account Representatives</description>
    <fields>
        <fullName>Rep_Number__c</fullName>
        <externalId>true</externalId>
        <label>Rep Number</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Rep</label>
    <nameField>
        <label>Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rep_Assignment__c.object
<CustomObject>
    <description>This is a relationship between a user and a rep, indicating that user should see that rep&apos;s records.</description>
    <fields>
        <fullName>Rep__c</fullName>
        <label>Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Rep Assignments</relationshipLabel>
        <relationshipName>Rep_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rep_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rep Assignment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Rep Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rep Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Rep_Split__c.object
<CustomObject>
    <fields>
        <fullName>Grant_Access_to_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Designates the rep being granted access to the Split Rep.</description>
        <inlineHelpText>Designates the rep being granted access to the Split Rep.</inlineHelpText>
        <label>Grant Access to Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Rep Splits (Grant Access to Rep)</relationshipLabel>
        <relationshipName>Rep_Splits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Split_Rep__c</fullName>
        <description>This is the rep we are splitting, i.e., granting access to other reps.</description>
        <label>Split Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Rep Splits</relationshipLabel>
        <relationshipName>Rep_Splits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rep Split</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Rep Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rep Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Davenport_Username__c</fullName>
        <label>Davenport Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Rep_SplitTriggerHandlerTest.cls
/**
 * Created by Eric Stansbury on 6/4/2019.
 */

@isTest
public class Rep_SplitTriggerHandlerTest {
    @isTest static void testHandleInsert(){
        User user = [Select id from user where davenport_username__c = :SecurityAssignmentTestFactory.davenportUsernameOne limit 1][0];
        Id rep1Id = [Select id from Rep__c where Rep_Number__c = 'REP1' limit 1][0].Id;
        Id rep3Id = [Select id from Rep__c where Rep_Number__c = 'REP3' limit 1][0].Id;

        integer shareCount;

        System.runAs(user){
            shareCount = [select count() from FinServ__FinancialAccount__c];
        }

        Test.startTest();
        // create a new rep split granting REP 1 access to REP 3
        Rep_Split__c repSplit = new Rep_Split__c(Split_Rep__c = rep3Id, Grant_Access_to_Rep__c = rep1Id);
        Rep_SplitTriggerHandler.handleAfterInsert(new List<Rep_Split__c>{ repSplit });
        Test.stopTest();
    }

    @isTest static void testHandleInsert2(){
        User user = [Select id from user where davenport_username__c = :SecurityAssignmentTestFactory.davenportUsernameOne limit 1][0];
        Id finAcctId = [Select Id from FinServ__FinancialAccount__c where Name = 'Financial Account Two (REP2)' limit 1][0].Id;
        Id rep1Id = [Select id from Rep__c where Rep_Number__c = 'REP1' limit 1][0].Id;
        Id rep2Id = [Select id from Rep__c where Rep_Number__c = 'REP2' limit 1][0].Id;

        Test.startTest();
        Rep_SplitTriggerHandler.handleAfterInsert(
            new List<Rep_Split__c>{
                new Rep_Split__c(
                    Split_Rep__c = rep2Id,
                    Grant_Access_to_Rep__c = rep1Id
                )
            }
        );
        Test.stopTest();
    }

    @isTest static void testHandleDelete(){
        User user = [Select id from user where davenport_username__c = :SecurityAssignmentTestFactory.davenportUsernameOne limit 1][0];
        Id rep1Id = [Select id from Rep__c where Rep_Number__c = 'REP1' limit 1][0].Id;
        Id rep3Id = [Select id from Rep__c where Rep_Number__c = 'REP3' limit 1][0].Id;
        Id finAcct3Id = [Select id from FinServ__FinancialAccount__c where Name = 'Financial Account Three (REP3)' limit 1][0].Id;
//        System.assertEquals(1, [select count() from rep_assignment__c where User__c = :user.Id and Rep__c = :rep1Id],
//            'User should have an existing rep 1 assignment from the test data.');
//        System.runAs(user){
//            System.assertEquals(0, [select count() from FinServ__FinancialAccount__c where Name = 'Financial Account Three (REP3)'],
//                    'User 1 should not be able to see finacct3.');
//        }

        // create a new rep split granting REP 1 access to REP 3

        Rep_Split__c repSplit = new Rep_Split__c(Split_Rep__c = rep3Id, Grant_Access_to_Rep__c = rep1Id);
        insert repSplit;

        Test.startTest();
        delete repSplit;
        Test.stopTest();

        // System.runAs(user){
        //     System.assertEquals(0, [select count() from FinServ__FinancialAccount__c where Name = 'Financial Account Three (REP3)'],
        //             'User 1 should no longer be able to see finacct3 via the rep split.');
        // }

        Rep_SplitTriggerHandler.handleAfterDelete(new List<Rep_Split__c>{ repSplit });
    }

    @TestSetup static void setupData(){
        SecurityAssignmentTestFactory.createData();
        delete [select id from account_split__c];
        delete [select id from rep_split__c];
        delete [select id from assistant_assignment__c];
    }
}