src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>FMA_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FMA Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Rep__c.object
<CustomObject>
    <description>Account Representatives</description>
    <label>Rep</label>
    <nameField>
        <label>Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FMAReviewControllerTest.cls
/**
 * Created by Eric Stansbury on 6/2/2019.
 */

@isTest
public class FMAReviewControllerTest {
    @isTest static void doTest(){
        Id finAcctId = [select id from finserv__financialaccount__c limit 1][0].Id;
        Id accountId = [Select id from account where RecordType.DeveloperName = 'Household_Client' and FMA_Account__c = true limit 1][0].Id;
        Id repId = [Select Id from Rep__c limit 1][0].Id;
        String personClientBtn = 'Reviewed, No Change';
        String investObjBtn = 'Reviewed, No Change';
        String timeHorizonBtn = 'Reviewed, No Change';
        String concenPositionsBtn = 'Reviewed, No Change';
        String highCashBtn = 'Reviewed, No Change';
        String tradingBtn = 'Reviewed, No Change';
        String investPerfBtn = 'Reviewed, No Change';

        String fmaReview = FMAReviewController.createFMAReview(
            'personClientComments',
            personClientBtn,
            'InvestObjComments',
            investObjBtn,
            'TimeHorzonComments',
            timeHorizonBtn,
            'InvestPerfComment',
            investPerfBtn,
            'ConcenPositionsComments',
            concenPositionsBtn,
            'HighCashComments',
            highCashBtn,
            'TradingComments',
            tradingBtn,
            repId,
            accountId,
            'CallNotes',
            'Subject',
            new List<String> { finAcctId }
        );

        System.assertNotEquals(null, fmaReview);
    }

    @TestSetup static void setupData(){
        SecurityAssignmentConfig.disableTriggers();

        SecurityAssignmentTestFactory.createData();
    }
}