src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_FMA_Form_Created__c</fullName>
        <label>Last FMA Form Created</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FMA_Account_Review_Association__c.object
<CustomObject>
    <fields>
        <fullName>FMA_Review_Form__c</fullName>
        <label>FMA Review Form</label>
        <referenceTo>FMA_Review_Form__c</referenceTo>
        <relationshipLabel>FMA Account - Review Associations</relationshipLabel>
        <relationshipName>FMA_Account_Review_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>FMA Account - Review Associations</relationshipLabel>
        <relationshipName>FMA_Account_Review_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>FMA Account - Review Association</label>
    <nameField>
        <displayFormat>FMA-Assoc-{0000}</displayFormat>
        <label>FMA Account - Review Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FMA Account - Review Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FMA_Review_Form__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>FMA Review Forms</relationshipLabel>
        <relationshipName>FMA_Review_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Notes__c</fullName>
        <label>Call Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Concentrated_Positions_Comments__c</fullName>
        <label>Concentrated Positions Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Concentrated_Positions_pl__c</fullName>
        <label>Concentrated Positions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>High_Cash_Balance_Comments__c</fullName>
        <label>High Cash Balance Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>High_Cash_Balance_pl__c</fullName>
        <label>High Cash Balance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investment_Objective_and_Risk_comments__c</fullName>
        <label>Investment Objective and Risk Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Investment_Objective_and_Risk_pl__c</fullName>
        <label>Investment Objective and Risk Tolerance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investment_and_Performance_Comments__c</fullName>
        <label>Investment and Performance Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Investment_and_Performance_pl__c</fullName>
        <label>Investment and Performance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Personal_Client_Info_co__c</fullName>
        <label>Personal Client Info Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Personal_Client_Info_pl__c</fullName>
        <label>Personal Client Info</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>FMA Review Forms</relationshipLabel>
        <relationshipName>FMA_Review_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Horizon_and_Liquidity_Needs_Comment__c</fullName>
        <label>Time Horizon and Liquidity Needs Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time_Horizon_pl__c</fullName>
        <label>Time Horizon and Liquidity Needs</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trading_Low_Trading_Comments__c</fullName>
        <label>Trading/Low Trading Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trading_Low_Trading_pl__c</fullName>
        <label>Trading/Low Trading</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FMA Review Form</label>
    <nameField>
        <displayFormat>FMA_Form-{0000}</displayFormat>
        <label>FMA Review Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FMA Review Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rep__c.object
<CustomObject>
    <description>Account Representatives</description>
    <label>Rep</label>
    <nameField>
        <label>Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FMAReviewController.cls
public with sharing class FMAReviewController {
    @AuraEnabled (cacheable=false)
    public static string createFMAReview(
        String personClientComments, 
        String personClientBtn, 
        String InvestObjComments, 
        String InvestObjBtn,
        String TimeHorzonComments,
        String TimeHorizonBtn,
        String InvestPerfComment,
        String InvestPerfBtn,
        String ConcenPositionsComments,
        String ConcenPositionsBtn,
        String HighCashComments,
        String HighCashBtn, 
        String TradingComments,
        String TradingBtn,
        String AccountRep,
        String AccountId,
        String CallNotes,
        String Subject,
        List <String> financialAcctsIds
    ){
        String message ='';

        FMA_Review_Form__c  fma =  new FMA_Review_Form__c();
        fma.Personal_Client_Info_pl__c = personClientBtn;
        fma.Personal_Client_Info_co__c = personClientComments;
        fma.Investment_Objective_and_Risk_comments__c = InvestObjComments;
        fma.Investment_Objective_and_Risk_pl__c = InvestObjBtn;
        fma.Time_Horizon_and_Liquidity_Needs_Comment__c = TimeHorzonComments;
        fma.Time_Horizon_pl__c = TimeHorizonBtn;
        fma.Investment_and_Performance_Comments__c = InvestPerfComment;
        fma.Investment_and_Performance_pl__c = InvestPerfBtn;
        fma.Concentrated_Positions_pl__c = ConcenPositionsBtn;
        fma.Concentrated_Positions_Comments__c = ConcenPositionsComments;
        fma.High_Cash_Balance_Comments__c = HighCashComments;
        fma.High_Cash_Balance_pl__c = HighCashBtn;
        fma.Trading_Low_Trading_pl__c = TradingBtn;
        fma.Trading_Low_Trading_Comments__c= TradingComments;
        fma.Rep__c = AccountRep;
        fma.Account__c = AccountId;
        fma.Call_Notes__c = CallNotes;
        fma.Subject__c = Subject;
        insert fma;


        Account acct = 
        [SELECT Id, Last_FMA_Form_Created__c FROM Account WHERE Id = :AccountId LIMIT 1];


        acct.Last_FMA_Form_Created__c = Date.today();

        update acct;

        // try{
        //     
        //     message = 'FMA form created ' + fma.Id;
        //     System.debug(message);
        //     return message;

        // }
        // catch(DmlException e) {
        //  System.debug('The following exception has occurred: ' + e.getMessage());
        //     return message;

        // }


        System.debug(financialAcctsIds.size());
        System.debug(financialAcctsIds);

		List<FMA_Account_Review_Association__c> toInsert = new List<FMA_Account_Review_Association__c>();

        for (Integer i=0; i<financialAcctsIds.size(); i++){

            toInsert.add(new FMA_Account_Review_Association__c(   
                FMA_Review_Form__c = fma.Id,
                Financial_Account__c = financialAcctsIds[i]
			));
		}
        insert toInsert;

        return fma.Id;
    }
}