src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_FMA_Form_Created__c</fullName>
        <label>Last FMA Form Created</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FMA_Review_Form__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>FMA Review Forms</relationshipLabel>
        <relationshipName>FMA_Review_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Notes__c</fullName>
        <label>Call Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Concentrated_Positions_pl__c</fullName>
        <label>Concentrated Positions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>High_Cash_Balance_pl__c</fullName>
        <label>High Cash Balance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investment_Objective_and_Risk_pl__c</fullName>
        <label>Investment Objective and Risk Tolerance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investment_and_Performance_pl__c</fullName>
        <label>Investment and Performance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legacy_CreatedDate__c</fullName>
        <label>Legacy Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Personal_Client_Info_pl__c</fullName>
        <label>Personal Client Info</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Horizon_pl__c</fullName>
        <label>Time Horizon and Liquidity Needs</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trading_Low_Trading_pl__c</fullName>
        <label>Trading/Low Trading</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FMA Review Form</label>
    <nameField>
        <displayFormat>FMA_Form-{0000}</displayFormat>
        <label>FMA Review Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FMA Review Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventToFMABatchable.cls
public class EventToFMABatchable implements Database.Batchable<SObject>{
	public Database.QueryLocator start(Database.BatchableContext BC){
    	return Database.getQueryLocator(
        	'Select Id, WhatId, Info_Reviewed__c, CreatedDate, Description, Subject from Task where Info_Reviewed__c != null'
        );
   	}

   	public void execute(Database.BatchableContext BC, List<sObject> scope){
		List<Task> Tasks = (List<Task>)scope;
        Set<Id> accountIds = new Set<Id>();
        List<FMA_Review_Form__c> insertMe = new List<FMA_Review_Form__c>();
        for (Task Task : Tasks){
            insertMe.add(
            	buildFMAReview(Task)
            );

            accountIds.add(Task.WhatId);
        }
        System.debug('EventToFMABatchable inserting ' + insertMe.size() + ' FMA Review forms');
        insert insertMe;

        Map<Id, Account> accounts = new Map<Id, Account>([Select Id, Last_FMA_Form_Created__c From Account Where Id in :accountIds]);

        for (Task Task : Tasks){
            Account acct = accounts.get(Task.WhatId);
            if (acct != null){
                acct.Last_FMA_Form_Created__c = Date.newInstance(Task.CreatedDate.year(), Task.CreatedDate.month(), Task.CreatedDate.day());
            }
        }
        
        update accounts.values();
    }

   	public void finish(Database.BatchableContext BC){
       	// do nothing
   	}
    
    // picklist values for FMA Review fields
    static String yes = 'Reviewed, No Change';
    static String no = 'Not Applicable';
    
    // Task -> FMA Review mapping here
    static FMA_Review_Form__c buildFMAReview(Task Task){
        FMA_Review_Form__c fmaReview = new FMA_Review_Form__c();
        fmaReview.Personal_Client_Info_pl__c 		  = (Task.Info_Reviewed__c.contains('Personal Client Info') ? yes : no );
        fmaReview.Investment_Objective_and_Risk_pl__c = (Task.Info_Reviewed__c.contains('Investment Objective & Risk Tolerance') ? yes : no );
        fmaReview.Time_Horizon_pl__c 				  = (Task.Info_Reviewed__c.contains('Time Horizon & Liquidity Needs') ? yes : no );
        fmaReview.Investment_and_Performance_pl__c 	  = (Task.Info_Reviewed__c.contains('Investments & Performance') ? yes : no );
        fmaReview.Concentrated_Positions_pl__c 		  = (Task.Info_Reviewed__c.contains('Concentrated Positions') ? yes : no );
        fmaReview.High_Cash_Balance_pl__c 			  = (Task.Info_Reviewed__c.contains('High Cash Balance') ? yes : no );
        fmaReview.Trading_Low_Trading_pl__c 		  = (Task.Info_Reviewed__c.contains('Unsolicited Trading/Low Trading') ? yes : no );
        fmaReview.Legacy_CreatedDate__c 			  = Task.CreatedDate;
        fmaReview.Call_Notes__c 					  = Task.Description;
        fmaReview.Subject__c 						  = Task.Subject;
        fmaReview.Account__c 						  = Task.WhatId;
        return fmaReview;
    }




}