src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cash_Value__c</fullName>
        <label>Cash Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Equity_Value__c</fullName>
        <label>Equity Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fixed_Income_Value__c</fullName>
        <label>Fixed Income Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Value__c</fullName>
        <label>Other Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Household_Percent__c.object
<CustomObject>
    <fields>
        <fullName>Household_Account__c</fullName>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Household Percents</relationshipLabel>
        <relationshipName>Household_Percents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Equities</fullName>
                </value>
                <value>
                    <fullName>Fixed Income</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Household Percent</label>
    <nameField>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Household Percents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/createPercentsTriggerTest.cls
@isTest
public class createPercentsTriggerTest {

    @isTest static void testCreatePercentRecords(){
        
        Account testAccount = new Account(Name = 'Test', Cash_Value__c = 1, Equity_Value__c = 2, Fixed_Income_Value__c = 3, Other_Value__c = 4);
        
        insert testAccount;
        
        Household_Percent__c perc = [SELECT Id, Value__c FROM Household_Percent__c WHERE Household_Account__c = :testAccount.Id AND Type__c = 'Cash'];  
        System.assertEquals(testAccount.Cash_Value__c, perc.Value__c);
        
    }
    
    @isTest static void testCreateNullValueRecords(){
        
        Account testAccount = new Account(Name = 'Test', Cash_Value__c = null, Equity_Value__c = null, Fixed_Income_Value__c = null, Other_Value__c = null);
        
        insert testAccount;
        
        Household_Percent__c perc = [SELECT Id, Value__c FROM Household_Percent__c WHERE Household_Account__c = :testAccount.Id AND Type__c = 'Cash'];  
        System.assertEquals(0.00, perc.Value__c);
        
        Household_Percent__c percF = [SELECT Id, Value__c FROM Household_Percent__c WHERE Household_Account__c = :testAccount.Id AND Type__c = 'Fixed Income'];  
        System.assertEquals(0.00, percF.Value__c);
        
        Household_Percent__c percO = [SELECT Id, Value__c FROM Household_Percent__c WHERE Household_Account__c = :testAccount.Id AND Type__c = 'Other'];  
        System.assertEquals(0.00, percO.Value__c);
        
        Household_Percent__c percE = [SELECT Id, Value__c FROM Household_Percent__c WHERE Household_Account__c = :testAccount.Id AND Type__c = 'Equities'];  
        System.assertEquals(0.00, percE.Value__c);
        
    }
    
    
}