src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_FMA_Form_Created__c</fullName>
        <label>Last FMA Form Created</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewDate__c</fullName>
        <description>Date of Last Review</description>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Rep__c.object
<CustomObject>
    <description>Account Representatives</description>
    <label>Rep</label>
    <nameField>
        <label>Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RepNumHouseholdSearchController.cls
public with sharing class RepNumHouseholdSearchController {

@AuraEnabled(cacheable=true)
  public static List<Account> getHouseholds(List<String> repNumbers){
      
        
        return [
            Select Id, Name, AccountNumber, Last_FMA_Form_Created__c, ReviewDate__c  from Account
            where Id in
                (Select FinServ__Household__c FROM FinServ__FinancialAccount__c
                 where Rep__c in :repNumbers) And Last_FMA_Form_Created__c != null
        ];
    }
}