src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewDate__c</fullName>
        <description>Date of Last Review</description>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FMA_Review_Form__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>FMA Review Forms</relationshipLabel>
        <relationshipName>FMA_Review_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Notes__c</fullName>
        <label>Call Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Concentrated_Positions_Comments__c</fullName>
        <label>Concentrated Positions Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Concentrated_Positions_pl__c</fullName>
        <label>Concentrated Positions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Create_Date__c</fullName>
        <formula>IF(NOT(ISBLANK(Legacy_CreatedDate__c)),Legacy_CreatedDate__c,CreatedDate)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Create Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>High_Cash_Balance_Comments__c</fullName>
        <label>High Cash Balance Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>High_Cash_Balance_pl__c</fullName>
        <label>High Cash Balance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investment_Objective_and_Risk_comments__c</fullName>
        <label>Investment Objective and Risk Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Investment_Objective_and_Risk_pl__c</fullName>
        <label>Investment Objective and Risk Tolerance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investment_and_Performance_Comments__c</fullName>
        <label>Investment and Performance Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Investment_and_Performance_pl__c</fullName>
        <label>Investment and Performance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Personal_Client_Info_co__c</fullName>
        <label>Personal Client Info Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Personal_Client_Info_pl__c</fullName>
        <label>Personal Client Info</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>FMA Review Forms</relationshipLabel>
        <relationshipName>FMA_Review_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Horizon_and_Liquidity_Needs_Comment__c</fullName>
        <label>Time Horizon and Liquidity Needs Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time_Horizon_pl__c</fullName>
        <label>Time Horizon and Liquidity Needs</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trading_Low_Trading_Comments__c</fullName>
        <label>Trading/Low Trading Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trading_Low_Trading_pl__c</fullName>
        <label>Trading/Low Trading</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FMA Review Form</label>
    <nameField>
        <displayFormat>FMA_Form-{0000}</displayFormat>
        <label>FMA Review Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FMA Review Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rep__c.object
<CustomObject>
    <description>Account Representatives</description>
    <label>Rep</label>
    <nameField>
        <label>Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FMADashboardController.cls
public with sharing class FMADashboardController {
   @AuraEnabled (cacheable=false)



	public static  Map<Id, List<FMA_Review_Form__c>> getFMAReviewData(List<Account> households, String startDateRange, String endDateRange){
       
		Map<Id, List<FMA_Review_Form__c>> mappedFMAForms = new Map<Id, List<FMA_Review_Form__c>>();

		Set<Id> ids = new Set<Id>();

		for (Account hh : households) {
			ids.add(hh.Id);
		}

		// parameters to your contoller method
		List<String> splitStartDate = startDateRange.split('-');    
		List<String> splitEndDate = endDateRange.split('-');   
		Date startDate = Date.newInstance(Integer.valueOf(splitStartDate[0]), Integer.valueOf(splitStartDate[1]), Integer.valueOf(splitStartDate[2]));
		Date endDate = Date.newInstance(Integer.valueOf(splitEndDate[0]), Integer.valueOf(splitEndDate[1]), Integer.valueOf(splitEndDate[2]));
		Time t = Time.newInstance(0,0,0,0);
		Datetime startDateTime = Datetime.newInstance(startDate,t);
		Datetime endDateTime = Datetime.newInstance(endDate.addDays(1),t);
		List<FMA_Review_Form__c> houseNotes = new List<FMA_Review_Form__c>();

        houseNotes = [
            SELECT 
                Account__c, 
                Rep__c, 
                Account__r.Name, 
                Account__r.ReviewDate__c,
                Rep__r.Name, 
                Account__r.AccountNumber,
                Account__r.Id,
                Concentrated_Positions_pl__c, 
                Concentrated_Positions_Comments__c,
                High_Cash_Balance_pl__c,
                High_Cash_Balance_Comments__c,
                Investment_and_Performance_pl__c,
                Investment_and_Performance_Comments__c,
                Investment_Objective_and_Risk_comments__c,
                Investment_Objective_and_Risk_pl__c,
                Personal_Client_Info_pl__c,
                Personal_Client_Info_co__c,
                Time_Horizon_pl__c,
                Time_Horizon_and_Liquidity_Needs_Comment__c,
                Trading_Low_Trading_pl__c,
                Trading_Low_Trading_Comments__c,
                Call_Notes__c,
                Create_Date__c
            FROM FMA_Review_Form__c 
            WHERE Account__r.Id IN :ids
            AND Create_Date__c >= :startDateTime
            AND Create_Date__c < :endDateTime
        ];

        for(FMA_Review_Form__c form : houseNotes){
			if (!mappedFMAForms.containsKey(form.Account__r.Id)) {
				mappedFMAForms.put(form.Account__r.Id, new List<FMA_Review_Form__c>());
			}
            mappedFMAForms.get(form.Account__r.Id).add(form);
		}

		 return mappedFMAForms;
   }
}