src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Rep__c.object
<CustomObject>
    <description>Account Representatives</description>
    <fields>
        <fullName>Rep_Number__c</fullName>
        <externalId>true</externalId>
        <label>Rep Number</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Rep</label>
    <nameField>
        <label>Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RepNumHouseholdSearchControllerTest.cls
/**
 * Created by Eric Stansbury on 6/2/2019.
 */

@isTest
public class RepNumHouseholdSearchControllerTest {
    @isTest static void doTest(){
        String repNumber = [Select Id from Rep__c where Rep_Number__c = 'REP1' limit 1][0].Id;

        List<Account> result = RepNumHouseholdSearchController.getHouseholds(new List<String>{repNumber});
        System.assertNotEquals(null, result);
    }

    @TestSetup static void setupData(){
        SecurityAssignmentTestFactory.createData();
    }
}