src/objects/Assistant_Assignment__c.object
<CustomObject>
    <description>Designates that a user is another user&apos;s assistant. A user can have multiple assistants and a user can be the assistant for multiple other users, so this is a junction object.</description>
    <fields>
        <fullName>Assistant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the user who is the assistant of the user designated by the &quot;Assistee&quot; ifeld.</description>
        <inlineHelpText>This is the user who is the assistant of the user designated by the &quot;Assistee&quot; ifeld.</inlineHelpText>
        <label>Assistant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assistant_Assignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assistant Assignment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Assistant Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assistant Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rep__c.object
<CustomObject>
    <description>Account Representatives</description>
    <label>Rep</label>
    <nameField>
        <label>Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rep_Security__c.object
<CustomObject>
    <fields>
        <fullName>Davenport_Username__c</fullName>
        <label>Davenport Username</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <label>GroupId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Rep Securities</relationshipLabel>
        <relationshipName>Rep_Securities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rep</fullName>
                    <default>true</default>
                    <label>Rep</label>
                </value>
                <value>
                    <fullName>UPI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rep_Securities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rep Security</label>
    <nameField>
        <label>Rep Security Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rep Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Davenport_Username__c</fullName>
        <label>Davenport Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SecurityRepSecurityGroupsBatchable.cls
global class SecurityRepSecurityGroupsBatchable implements Database.Batchable<SObject>, Database.Stateful {

	String log;
	List<Id> testUserIds;
	
	global SecurityRepSecurityGroupsBatchable() {
		log = '';
	}
	
	global SecurityRepSecurityGroupsBatchable(List<Id> testUserIds) {
		log = '';
		this.testUserIds = testUserIds;
	}

	global Database.QueryLocator start(Database.BatchableContext context) {
		if (null != testUserIds && testUserIds.size() > 0) {
			return Database.getQueryLocator([
				SELECT
					Davenport_Username__c,
					UPI_GroupId__c,
					( SELECT
						Rep__r.GroupId__c,
						Type__c
					FROM Rep_Securities__r ),
					(
						SELECT
							Assistant__c
						FROM Assistants__r
					)
				FROM User
				WHERE Id IN :testUserIds
			]);
		} else {
			return Database.getQueryLocator([
				SELECT
					Davenport_Username__c,
					UPI_GroupId__c,
					( SELECT
						Rep__r.GroupId__c,
						Type__c
					FROM Rep_Securities__r ),
					(
						SELECT
							Assistant__c
						FROM Assistants__r
					)
				FROM User
			]);
		}
	}

   	global void execute(Database.BatchableContext context, List<User> scope) {

		Map<Id,User> mapUserIdToUser = new Map<Id,User>();
		Map<Id,Set<Id>> mapUserIdToRepGroupIds = new Map<Id,Set<Id>>();
		Map<Id,Set<Id>> mapUserIdToUPIRepGroupIds = new Map<Id,Set<Id>>();

		// find the Rep groups where the user has access and sort them by Type
		for (User usr : scope) {
			mapUserIdToUser.put(usr.Id, usr);

			for (Rep_Security__c repSeurity : usr.Rep_Securities__r) {
				if (null != repSeurity.Rep__c && null != repSeurity.Rep__r.GroupId__c) {
					if ('Rep' == repSeurity.Type__c) {
						if (!mapUserIdToRepGroupIds.containsKey(usr.Id)) {
							mapUserIdToRepGroupIds.put(usr.Id, new Set<Id>());
						}
						mapUserIdToRepGroupIds.get(usr.Id).add(repSeurity.Rep__r.GroupId__c);
					} else {
						if (!mapUserIdToUPIRepGroupIds.containsKey(usr.Id)) {
							mapUserIdToUPIRepGroupIds.put(usr.Id, new Set<Id>());
						}
						mapUserIdToUPIRepGroupIds.get(usr.Id).add(repSeurity.Rep__r.GroupId__c);
					}
				}
			}
		}

		Map<Id,Group> mapUserIdToGroupforUPIAccess = new Map<Id,Group>();

		// remove UPI Rep groups where the user already has access using a Rep Group
		for (Id usrId : mapUserIdToUPIRepGroupIds.keySet()) {
			User usr = mapUserIdToUser.get(usrId);

			if (mapUserIdToRepGroupIds.containsKey(usrId)) {
				mapUserIdToUPIRepGroupIds.get(usrId).removeAll(mapUserIdToRepGroupIds.get(usrId));
			}
			// create a group for each user that has UPI groups left
			if (mapUserIdToUPIRepGroupIds.get(usrId).size() > 0) {
				mapUserIdToGroupforUPIAccess.put(usrId, new Group(
					Name = 'Rep-UPI-' + usr.Davenport_Username__c + '-' + usrId,
					Type = 'Regular'
				));
			}
		}

		// insert the UPI user groups
		insert mapUserIdToGroupforUPIAccess.values();

		List<GroupMember> groupMembers = new List<GroupMember>();

		// add the UPI User groups as members to the UPI rep Groups
		for (Id usrId : mapUserIdToGroupforUPIAccess.keySet()) {
			User usr = mapUserIdToUser.get(usrId);

			usr.UPI_GroupId__c = mapUserIdToGroupforUPIAccess.get(usrId).Id;
			for (Id repGroupId : mapUserIdToUPIRepGroupIds.get(usrId)) {
				groupMembers.add(new GroupMember(
					GroupId = repGroupId,
					UserOrGroupId = usr.UPI_GroupId__c
				));
			}
		}

		// save the UPI Group Ids to the users that got them
		List<User> usersToUpdate = new List<User>();
		for (Id usrId : mapUserIdToGroupforUPIAccess.keySet()) {
			usersToUpdate.add(mapUserIdToUser.get(usrId));
		}
		update usersToUpdate;

		// add the user and assistants as members to the Rep type groups
		for (Id usrId : mapUserIdToRepGroupIds.keySet()) {
			User usr = mapUserIdToUser.get(usrId);

			for (Id repGroupId : mapUserIdToRepGroupIds.get(usrId)) {
				groupMembers.add(new GroupMember(
					GroupId = repGroupId,
					UserOrGroupId = usrId
				));
				for (Assistant_Assignment__c assistant : usr.Assistants__r) {
					groupMembers.add(new GroupMember(
						GroupId = repGroupId,
						UserOrGroupId = assistant.Assistant__c
					));
				}
			}
		}
		insert groupMembers;
	}
	
	global void finish(Database.BatchableContext context) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[] {UserInfo.getUserEmail()});
        mail.setSenderDisplayName('SecurityRepSecurityGroupsBatchable');
        mail.setSubject('SecurityRepSecurityGroupsBatchable Completed');
        mail.setPlainTextBody('Job ID: ' + context.getJobId() + log);
        if (!Test.isRunningTest()){
            try {
                Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                        mail
                });
            }catch(EmailException e){
                // usually just means NO_MASS_MAIL_PERMISSION -- email failing shouldn't prevent next step from executing
                System.debug(e);
            }

			Database.executeBatch(new SecurityFinancialAccountBatchable());
        }
	}
}