src/objects/FMA_Review_Form__c.object
<CustomObject>
    <fields>
        <fullName>Call_Notes__c</fullName>
        <label>Call Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Concentrated_Positions_Comments__c</fullName>
        <label>Concentrated Positions Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Concentrated_Positions_pl__c</fullName>
        <label>Concentrated Positions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>High_Cash_Balance_Comments__c</fullName>
        <label>High Cash Balance Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>High_Cash_Balance_pl__c</fullName>
        <label>High Cash Balance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investment_Objective_and_Risk_comments__c</fullName>
        <label>Investment Objective and Risk Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Investment_Objective_and_Risk_pl__c</fullName>
        <label>Investment Objective and Risk Tolerance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Investment_and_Performance_Comments__c</fullName>
        <label>Investment and Performance Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Investment_and_Performance_pl__c</fullName>
        <label>Investment and Performance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Personal_Client_Info_co__c</fullName>
        <label>Personal Client Info Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Personal_Client_Info_pl__c</fullName>
        <label>Personal Client Info</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Horizon_and_Liquidity_Needs_Comment__c</fullName>
        <label>Time Horizon and Liquidity Needs Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Time_Horizon_pl__c</fullName>
        <label>Time Horizon and Liquidity Needs</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trading_Low_Trading_Comments__c</fullName>
        <label>Trading/Low Trading Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trading_Low_Trading_pl__c</fullName>
        <label>Trading/Low Trading</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                    <default>true</default>
                    <label>Not Applicable</label>
                </value>
                <value>
                    <fullName>Reviewed, No Change</fullName>
                </value>
                <value>
                    <fullName>Review Changes as Follows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FMA Review Form</label>
    <nameField>
        <displayFormat>FMA_Form-{0000}</displayFormat>
        <label>FMA Review Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FMA Review Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FormData__c.object
<CustomObject>
    <fields>
        <fullName>Forms_For_VF_Page__c</fullName>
        <label>Forms For VF Page</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>FormData</label>
    <nameField>
        <displayFormat>FormData - {0000}</displayFormat>
        <label>FormData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FormData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FMAReviewPDFController_Test.cls
@isTest
public class FMAReviewPDFController_Test {
    
    private static Id createReview(Integer type) {
        FMA_Review_Form__c review = new FMA_Review_Form__c();
        if (1 == type) {
            review.Concentrated_Positions_pl__c = 'Review Changes as Follows';
            review.Concentrated_Positions_Comments__c = 'test comment';
            review.High_Cash_Balance_pl__c = 'Reviewed, No Change';
            review.High_Cash_Balance_Comments__c = '';
            review.Investment_and_Performance_pl__c = 'Review Changes as Follows';
            review.Investment_and_Performance_Comments__c = 'test comment';
            review.Investment_Objective_and_Risk_pl__c = 'Reviewed, No Change';
            review.Investment_Objective_and_Risk_comments__c = '';
            review.Personal_Client_Info_pl__c = 'Review Changes as Follows';
            review.Personal_Client_Info_co__c = 'test comment';
            review.Time_Horizon_pl__c = 'Reviewed, No Change';
            review.Time_Horizon_and_Liquidity_Needs_Comment__c = '';
            review.Trading_Low_Trading_pl__c = 'Review Changes as Follows';
            review.Trading_Low_Trading_Comments__c = 'test comment';
            review.Call_Notes__c = '';
        } else {
            review.Concentrated_Positions_pl__c = 'Reviewed, No Change';
            review.Concentrated_Positions_Comments__c = '';
            review.High_Cash_Balance_pl__c = 'Review Changes as Follows';
            review.High_Cash_Balance_Comments__c = 'test comment';
            review.Investment_and_Performance_pl__c = 'Reviewed, No Change';
            review.Investment_and_Performance_Comments__c = '';
            review.Investment_Objective_and_Risk_pl__c = 'Review Changes as Follows';
            review.Investment_Objective_and_Risk_comments__c = 'test comment';
            review.Personal_Client_Info_pl__c = 'Reviewed, No Change';
            review.Personal_Client_Info_co__c = '';
            review.Time_Horizon_pl__c = 'Review Changes as Follows';
            review.Time_Horizon_and_Liquidity_Needs_Comment__c = 'test comment';
            review.Trading_Low_Trading_pl__c = 'Reviewed, No Change';
            review.Trading_Low_Trading_Comments__c = '';
            review.Call_Notes__c = 'more comments';
        }
        insert review;
        return review.Id;
    }
    
    private static Id getFormDataId() {
        String formsForVFPage = '';
        formsForVFPage += createReview(1);
        formsForVFPage += ',' + createReview(2);
        formsForVFPage += ',' + createReview(2);
        formsForVFPage += ',' + createReview(1);
        
        FormData__c formData = new FormData__c();
        formData.Forms_For_VF_Page__c = formsForVFPage;
        insert formData;
        
        return formData.Id;
    }
    
    @isTest private static void testOne() {
        PageReference FMAReviewPDF = new PageReference('/apex/FMAReviewPDF?formDataId=' + getFormDataId());
        Test.setCurrentPage(FMAReviewPDF);
        //ApexPages.currentPage().getParameters().put('formDataId', getFormDataId());
        FMAReviewPDFController inst = new FMAReviewPDFController();
        system.assertNotEquals(null, inst.formData);
        system.assertEquals(false, inst.getIsDraft());
        system.assertNotEquals(null, inst.getReviews());
        system.assertNotEquals(null, inst.getHouseHoldReviews());
        //system.assertNotEquals(null, inst.formData);
    }
    
}