src/objects/FormData__c.object
<CustomObject>
    <fields>
        <fullName>Forms_For_VF_Page__c</fullName>
        <label>Forms For VF Page</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RepUserName__c</fullName>
        <label>RepUserName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>FormData</label>
    <nameField>
        <displayFormat>FormData - {0000}</displayFormat>
        <label>FormData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FormData</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FormDataController.cls
public with sharing class FormDataController {
  @AuraEnabled (cacheable=false)
  public static String createFormData(String formIds, String repLabel){

    
   
      FormData__c form = new FormData__c();
      form.Forms_For_VF_Page__c = formIds;
      form.RepUserName__c = repLabel;


      try {
          insert form;
          System.debug(form.Id);
          return form.Id;
      }
      catch(DmlException e){
         System.debug('The following exception has occurred: ' + e.getMessage());
            return e.getMessage(); 
      }
      
  }
}