src/objects/Rep_Security__c.object
<CustomObject>
    <fields>
        <fullName>Davenport_Username__c</fullName>
        <label>Davenport Username</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rep_Number__c</fullName>
        <label>Rep Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rep</fullName>
                    <default>true</default>
                    <label>Rep</label>
                </value>
                <value>
                    <fullName>UPI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rep Security</label>
    <nameField>
        <label>Rep Security Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rep Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RepSecurityInitializationScript.cls
/**
 * Created by Eric Stansbury on 7/25/2019.
 */

global class RepSecurityInitializationScript implements Database.Batchable<SObject>{
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator('Select Id, Davenport_Username__c, Rep_Number__c, Type__c from Rep_Security__c');
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        Rep_SecurityTriggerHandler.handleAfterInsert(scope);
    }

    global void finish(Database.BatchableContext BC) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[] {UserInfo.getUserEmail()});
        mail.setSenderDisplayName('RepSecurityInitializationScript');
        mail.setSubject('RepSecurityInitializationScript Completed');
        mail.setPlainTextBody('Job ID: ' + bc.getJobId());
        if (!Test.isRunningTest()){
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{ mail });
        }
    }
}