src/objects/Rep__c.object
<CustomObject>
    <description>Account Representatives</description>
    <label>Rep</label>
    <nameField>
        <label>Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rep_Security__c.object
<CustomObject>
    <fields>
        <fullName>Davenport_Username__c</fullName>
        <label>Davenport Username</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <label>GroupId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Rep Securities</relationshipLabel>
        <relationshipName>Rep_Securities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rep</fullName>
                    <default>true</default>
                    <label>Rep</label>
                </value>
                <value>
                    <fullName>UPI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Rep Security</label>
    <nameField>
        <label>Rep Security Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rep Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Davenport_Username__c</fullName>
        <label>Davenport Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Firm_Wide_Access_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Firm Wide Access Enabled</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UPIAccessToggleController.cls
/*
    This is the controller for a Lightning component which allows a Branch Manager user to manually toggle their UPI assignments on and off

    Rep Security records come in as either 'Rep' type or 'UPI' type. UPI assignments include visibility for branch managers and so on, whereas Rep assignments
        are "book of business" assignments -- i.e., the rep numbers you actually work on day to day. Users need the ability to toggle between "Firm Wide Access"
        (UPI assignments + rep assignments) and "Rep Access" (rep assignments only). On the backend, switching to "Rep Access" will remove the user's access to records
        which they can only see because of a UPI assignment. Switching back to "Firm Wide Access" will grant their access back to the reps via the UPI records.
 */
public without sharing class UPIAccessToggleController {
    @AuraEnabled public static boolean isFirmwideAccessEnabled(){
        User myUser = [
			Select
				Firm_Wide_Access_Enabled__c
			FROM User
			WHERE Id = :UserInfo.getUserId()
			LIMIT 1
		];
        return myUser.Firm_Wide_Access_Enabled__c;
    }

    @AuraEnabled public static void enableUPIAccess(){
		Id userId = UserInfo.getUserId();

		User currentUser = [
			SELECT
				Davenport_Username__c
			FROM User
			WHERE Id = :userId
		];

		List<Rep_Security__c> upiRepSecurities = [
			SELECT
				Rep__r.GroupId__c,
				GroupId__c
			FROM Rep_Security__c
			WHERE Type__c = 'UPI'
			AND Davenport_Username__c = :currentUser.Davenport_Username__c
		];

		List<GroupMember> groupMembers = new List<GroupMember>();

		for (Rep_Security__c repSecurity : upiRepSecurities) {
			groupMembers.add(new GroupMember(
				GroupId = repSecurity.Rep__r.GroupId__c,
				UserOrGroupId = repSecurity.GroupId__c));
		}

		insert groupMembers;
		currentUser.Firm_Wide_Access_Enabled__c = true;
		update currentUser;
    }

    @AuraEnabled public static void disableUPIAccess(){
		Id userId = UserInfo.getUserId();

		User currentUser = [
			SELECT
				Davenport_Username__c
			FROM User
			WHERE Id = :userId
		];

		List<Rep_Security__c> upiRepSecurities = [
			SELECT
				GroupId__c
			FROM Rep_Security__c
			WHERE Type__c = 'UPI'
			AND Davenport_Username__c = :currentUser.Davenport_Username__c
		];

		List<Id> upiGroupIds = new List<Id>();
		for (Rep_Security__c repSecurity : upiRepSecurities) {
			upiGroupIds.add(repSecurity.GroupId__c);
		}

		List<GroupMember> groupMembers = [
			SELECT
				Id
			FROM GroupMember
			WHERE UserOrGroupId IN :upiGroupIds
		];

		delete groupMembers;
		currentUser.Firm_Wide_Access_Enabled__c = false;
		update currentUser;
    }
}