src/objects/Rep__c.object
<CustomObject>
    <description>Account Representatives</description>
    <fields>
        <fullName>Rep_Number__c</fullName>
        <externalId>true</externalId>
        <label>Rep Number</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Rep</label>
    <nameField>
        <label>Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rep_Split__c.object
<CustomObject>
    <fields>
        <fullName>Grant_Access_to_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Designates the rep being granted access to the Split Rep.</description>
        <inlineHelpText>Designates the rep being granted access to the Split Rep.</inlineHelpText>
        <label>Grant Access to Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Rep Splits (Grant Access to Rep)</relationshipLabel>
        <relationshipName>Rep_Splits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Split_Rep__c</fullName>
        <description>This is the rep we are splitting, i.e., granting access to other reps.</description>
        <label>Split Rep</label>
        <referenceTo>Rep__c</referenceTo>
        <relationshipLabel>Rep Splits</relationshipLabel>
        <relationshipName>Rep_Splits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rep Split</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Rep Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rep Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestSecurityRepSplitsBatchable.cls
@isTest 
private class TestSecurityRepSplitsBatchable {

	@isTest
	private static void testRepSplits() {
		Rep__c rep1 = new Rep__c(
			Rep_Number__c = 'TS01'
		);
		insert rep1;

		Rep__c rep2 = new Rep__c(
			Rep_Number__c = 'TS02'
		);
		insert rep2;

		Rep__c rep3 = new Rep__c(
			Rep_Number__c = 'TS03'
		);
		insert rep3;

		Group groupRep1 = new Group(
			Name = 'Rep-' + rep1.Rep_Number__c + '-' + rep1.Id
		);
		insert groupRep1;
		rep1.GroupId__c = groupRep1.Id;
		update rep1;

		Group groupRep2 = new Group(
			Name = 'Rep-' + rep2.Rep_Number__c + '-' + rep2.Id
		);
		insert groupRep2;
		rep2.GroupId__c = groupRep2.Id;
		update rep2;

		Group groupRep3 = new Group(
			Name = 'Rep-' + rep3.Rep_Number__c + '-' + rep3.Id
		);
		insert groupRep3;
		rep3.GroupId__c = groupRep3.Id;
		update rep3;


		Rep_Split__c repSplit1_2 = new Rep_Split__c(
			Split_Rep__c = rep2.Id,
			Grant_Access_to_Rep__c = rep1.Id
		);
		insert repSplit1_2;

		Rep_Split__c repSplit1_3 = new Rep_Split__c(
			Split_Rep__c = rep3.Id,
			Grant_Access_to_Rep__c = rep1.Id
		);
		insert repSplit1_3;


		Test.startTest();
		Database.executeBatch(new SecurityRepSplitsBatchable());
		Test.stopTest();

		List<GroupMember> groupMembers = [
			SELECT
				GroupId,
				UserOrGroupId
			FROM GroupMember
			WHERE GroupId = :groupRep1.Id
		];

		List<GroupMember> groupMembers1_2 = [
			SELECT
				GroupId,
				UserOrGroupId
			FROM GroupMember
			WHERE GroupId = :groupRep1.Id
			AND UserOrGroupId = :groupRep2.Id
		];

		List<GroupMember> groupMembers1_3 = [
			SELECT
				GroupId,
				UserOrGroupId
			FROM GroupMember
			WHERE GroupId = :groupRep1.Id
			AND UserOrGroupId = :groupRep3.Id
		];

		System.assertEquals(2, groupMembers.size());
		System.assertEquals(1, groupMembers1_2.size());
		System.assertEquals(1, groupMembers1_3.size());
	}
}